#
# go build vs. go run vs. go install 
# https://levelup.gitconnected.com/go-run-vs-go-build-vs-go-install-c7c0fd135cf9
#

build:
	go build .

# equivalently: go run ./99-advanced/structural-design-patterns/adapter
run:
	go run .